name: Mayur, Work To Live The Dream
markdown: kramdown
kramdown:
 input: GFM
 highlighter: rouge
permalink: /blog/:year/:month/:day/:title

collections:
  deep-learning:
    output: true
  machine-learning:
    output: true
    
---
layout: default
comments: true
# other options
---

# Google services
google_analytics: UA-108823315-1

