name: Mayur, Work To Live The Dream
markdown: kramdown
kramdown:
 input: GFM
 highlighter: rouge
permalink: /blog/:year/:month/:day/:title

collections:
  notebooks:
    output: true
    
# Google services
google_analytics: UA-108823315-1

